// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearScreenshots() {
  return window['go']['main']['App']['ClearScreenshots']();
}

export function CountItems() {
  return window['go']['main']['App']['CountItems']();
}

export function DownloadIcons() {
  return window['go']['main']['App']['DownloadIcons']();
}

export function GetGeminiKey() {
  return window['go']['main']['App']['GetGeminiKey']();
}

export function GetHideoutStations() {
  return window['go']['main']['App']['GetHideoutStations']();
}

export function GetItemRequirements() {
  return window['go']['main']['App']['GetItemRequirements']();
}

export function GetManualPrompt() {
  return window['go']['main']['App']['GetManualPrompt']();
}

export function GetQuests() {
  return window['go']['main']['App']['GetQuests']();
}

export function GetSyncInfo() {
  return window['go']['main']['App']['GetSyncInfo']();
}

export function HasGeminiKey() {
  return window['go']['main']['App']['HasGeminiKey']();
}

export function ParseManualJSON(arg1) {
  return window['go']['main']['App']['ParseManualJSON'](arg1);
}

export function SaveGeminiKey(arg1) {
  return window['go']['main']['App']['SaveGeminiKey'](arg1);
}

export function ScanStash() {
  return window['go']['main']['App']['ScanStash']();
}

export function SetHideoutStationLevel(arg1, arg2) {
  return window['go']['main']['App']['SetHideoutStationLevel'](arg1, arg2);
}

export function SyncHideoutAndQuests() {
  return window['go']['main']['App']['SyncHideoutAndQuests']();
}

export function UpdateStash(arg1) {
  return window['go']['main']['App']['UpdateStash'](arg1);
}
