// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearScreenshots():Promise<void>;

export function CountItems():Promise<number>;

export function DownloadIcons():Promise<void>;

export function GetGeminiKey():Promise<string>;

export function GetHideoutStations():Promise<Array<main.HideoutStationDTO>>;

export function GetItemRequirements():Promise<Array<main.ItemRequirementDTO>>;

export function GetManualPrompt():Promise<string>;

export function GetQuests():Promise<Array<main.QuestDTO>>;

export function GetSyncInfo():Promise<main.SyncInfoDTO>;

export function HasGeminiKey():Promise<boolean>;

export function ParseManualJSON(arg1:string):Promise<main.StashResultDTO>;

export function SaveGeminiKey(arg1:string):Promise<void>;

export function ScanStash():Promise<main.StashResultDTO>;

export function SetHideoutStationLevel(arg1:string,arg2:number):Promise<void>;

export function SyncHideoutAndQuests():Promise<void>;

export function UpdateStash(arg1:Array<main.StashItemDTO>):Promise<void>;
